services:
  - docker:dind

stages:
  - build

build-development:
  stage: build
  image: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - docker:dind
  before_script:
    - apk update && apk add git && apk add python3
    - git remote set-url origin https://CI_PUSH_TOKEN:${CI_PUSH_TOKEN}@gitlab.com/dishenmakwana/nestjs-api.git
    - git checkout development
    - git config --local user.email 'gitlab_runner@gmail.com'
    - git config --local user.name 'Gitlab Runner'
    - echo "$CI_REGISTRY"
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY --username $CI_DEPLOY_USER --password-stdin
    - image_name=nestjs-api
  script:
    - git config pull.rebase false
    - git pull origin development
    - ls
    - ls scripts
    - last_commit_message=`git log -1 --pretty=%B | cat`
    - echo "$last_commit_message"
    - python3 scripts/version_bump.py --commit="$last_commit_message"
    - version=`cat VERSION`
    - git add -A
    - git commit -m "version $version [skip ci]"
    - git tag -a "v$version" -m "version $version [skip ci]"
    - docker build -t $DOCKER_REGISTRY/$image_name:latest-development .
    - docker tag $DOCKER_REGISTRY/$image_name:latest-development $DOCKER_REGISTRY/$image_name:$version
    - docker push $DOCKER_REGISTRY/$image_name:$version
    - docker push $DOCKER_REGISTRY/$image_name:latest-development
    - git push
    - git push --tags
  only:
    - development

build-staging:
  stage: build
  image: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - docker:dind
  before_script:
    - apk update && apk add git && apk add python3
    - git remote set-url origin https://CI_PUSH_TOKEN:${CI_PUSH_TOKEN}@gitlab.com/dishenmakwana/nestjs-api.git
    - git checkout staging
    - git config --local user.email 'gitlab_runner@gmail.com'
    - git config --local user.name 'Gitlab Runner'
    - echo "$CI_REGISTRY"
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY --username $CI_DEPLOY_USER --password-stdin
    - image_name=nestjs-api
  script:
    - git config pull.rebase false
    - git pull origin staging
    - docker build -t $DOCKER_REGISTRY/$image_name:latest-staging .
    - docker tag $DOCKER_REGISTRY/$image_name:latest-staging
    - docker push $DOCKER_REGISTRY/$image_name:latest-staging
    - git push
    - git push --tags

  only:
    - staging

build-production:
  stage: build
  image: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - docker:dind
  before_script:
    - apk update && apk add git && apk add python3
    - git remote set-url origin https://CI_PUSH_TOKEN:${CI_PUSH_TOKEN}@gitlab.com/dishenmakwana/nestjs-api.git
    - git checkout production
    - git config --local user.email 'gitlab_runner@gmail.com'
    - git config --local user.name 'Gitlab Runner'
    - echo "$CI_REGISTRY"
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY --username $CI_DEPLOY_USER --password-stdin
    - image_name=nestjs-api
  script:
    - git config pull.rebase false
    - git pull origin production
    - docker build -t $DOCKER_REGISTRY/$image_name:latest-production .
    - docker tag $DOCKER_REGISTRY/$image_name:latest-production
    - docker push $DOCKER_REGISTRY/$image_name:latest-production
    - git push
    - git push --tags

  only:
    - production