version: '3.8'
services:
  soketi:
    container_name: soketi
    image: quay.io/soketi/soketi:1.4-16-alpine
    restart: always
    environment:
      - SOKETI_DEBUG=1
      - SOKETI_DEFAULT_APP_ID=KrHBrG0Jpx
      - SOKETI_DEFAULT_APP_KEY=1A452AnQZ95d1485c
      - SOKETI_DEFAULT_APP_SECRET=v514k356a8qj475a7426h5
      - METRICS_SERVER_PORT=9601
    ports:
      - '6001:6001'
      - '9601:9601'
