version: '3'
services:
  api:
    container_name: nestjs-template
    image: registry.gitlab.com/project_name:v0.0.1
    restart: always
    environment:
      - PORT=80
      - DATABASE_URL=mysql://username:password@connection_url/database_name
      - ACCESS_TOKEN_SECRET=ACCESSTOKENSECRET
      - ACCESS_TOKEN_EXPIRES_IN=7d
      - MAIL_FROM=no-reply@nestjs.com
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USER=username
      - MAIL_PASSWORD=password
      - MAIL_SECURE=false
      - FRONTEND_BASE_URL=http://127.0.0.1:8080
      - RUN_MIGRATION=false
      - RUN_SEED=false
    ports:
      - '5000:80'
