version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    # environment:
    #   - REDIS_PASSWORD=Admin@123
    # command: redis-server --requirepass Admin@123
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
volumes:
  redis-data:
