export const apiDesc = {
  config: {
    createConfig: 'Create Config',
    configList: 'Config list',
    configDetails: 'Config details',
    updateConfig: 'Update Config',
    deleteConfig: 'Delete Config',
    allConfig: 'All config',
    ConfigSearch: 'Config search',
  },
  task: {
    handleExpiredTokens: 'Handle expired tokens',
  },
  user: {
    profileData: 'Profile data',
    profilePhotoUpdate: 'Profile photo update',
    profileUpdate: 'Profile update',
    testPusher: 'Test pusher',
    testEmail: 'Test email',
    testNotification: 'Test notification',
    testAWSUploadFile: 'Test AWS upload file',
    testRedis: 'Test redis',
  },
  auth: {
    login: 'Login',
    logout: 'Logout',
    forgotPassword: 'Forgot password',
    verifyOTP: 'Verify OTP',
    resetPassword: 'Reset password',
    changePassword: 'Change password',
    resentVerificationEmail: 'Resent verification email',
    register: 'Register',
    verifyUser: 'Verify user',
    socialRegister: 'Social register',
    socialLogin: 'Social login',
  },
  admin: {
    userList: 'User list',
    userDetails: 'User details',
    updateConfig: 'Update config',
  },
};
