export const message = {
  SUCCESS_RESPONSE: 'Success.',
  INTERNAL_SERVER_ERROR: 'Internal server error.',
  validate: {
    email: 'Please enter valid email.',
    password:
      'Password must contain 8 characters including uppercase, lowercase, digits and special character.',
    url: 'Invalid url.',
    latitude: 'Invalid latitude.',
    longitude: 'Invalid longitude.',
  },
  common: {
    INVALID_SORT_COLUMN: 'Invalid sort column.',
    INVALID_SORT_ORDER: 'Invalid sort order.',
  },
  user: {
    PROFILE_DATA: 'Profile data fetch successfully.',
    PROFILE_PHOTO_UPDATE: 'Profile photo updated successfully.',
    PROFILE_UPDATE: 'Profile updated successfully.',
    TEST_PUSHER: 'Test pusher.',
    TEST_EMAIL: 'Test email.',
    TEST_NOTIFICATION: 'Test notification.',
    TEST_AWS_UPLOAD_FILE: 'Test AWS upload file.',
    INVALID_GOOGLE_TOKEN: 'Invalid google token.',
    INVALID_REQUEST: 'Invalid request.',
    INVALID_OTP: 'Invalid otp.',
    USER_NOT_FOUND: 'User not found.',
    USER_ALREADY_EXISTS: 'User already exists.',
    USER_ALREADY_VERIFIED: 'User already verified.',
    INVALID_CURRENT_PASSWORD: 'Invalid current password.',
    SAME_PASSWORD: 'New password must be different from old password.',
    USE_DIFFERENT_PASSWORD: 'Please use different password.',
    USER_NOT_VERIFIED: 'User not verified.',
    USER_NOT_ONBOARDED: 'User not onboarded.',
    INVALID_CRED: 'Invalid credentials.',
    SUCCESS_LOGIN: 'Login successfully.',
    SUCCESS_LOGOUT: 'Logout successfully.',
    FORGOT_PASSWORD: 'OTP sent successfully.',
    OTP_VERIFIED: 'OTP verified successfully.',
    SUCCESS_PASSWORD_CHANGED: 'Password changed successfully.',
    RESENT_VERIFICATION_EMAIL: 'Verification email sent successfully.',
    REGISTRATION_SUCCESSFULLY: 'Registration successfully.',
    VERIFICATION_SUCCESSFULLY: 'Verification successfully.',
    SUCCESS_SOCIAL_REGISTER: 'Social register success.',
    SUCCESS_SOCIAL_LOGIN: 'Social login success.',
    TEST_REDIS: 'Test redis.',
    TEST_CACHE: 'Test cache.',
  },
  admin: {
    USER_DETAILS: 'User details fetch successfully.',
    USER_LIST: 'User list fetch successfully.',
  },
  task: {
    HANDLE_DELETE_OLD_LOGS: 'Handle delete old logs.',
  },
};
