export const message = {
  SUCCESS_RESPONSE: 'Success Response.',
  SUCCESS_LIST: 'Listed successfully.',
  SUCCESS_VIEW: 'Viewed successfully.',
  SUCCESS_GET: 'Got successfully.',
  SUCCESS_CREATE: 'Created successfully.',
  SUCCESS_UPDATE: 'Updated successfully.',
  SUCCESS_DELETE: 'Deleted successfully.',
  MANDATORY_FIELDS: 'Please fill mandatory data.',
  MISSING_FIELDS: 'Please fill all the fields.',
  VALIDATION_ERROR: 'Validation Error.',
  DATA_NOT_FOUND: 'Data not found.',
  MISSING_DATA: 'Missing some data.',
  SOMETHING_WENTS_WRONG: 'Something wents wrong.',
  UNAUTHORIZED: "You don't have permission.",
  user: {
    SUCCESS_LOGIN: 'Login Successfully.',
    SUCCESS_REGISTER: 'Register Successfully.',
    USER_ACCOUNT_DEACTIVATED: 'The account is not verified yet.',
    USER_ACCOUNT_UNVERIFIED: 'Your account has been deactivated.',
    NO_ACCESS: "You don't have access.",
    SESSION_TIMEOUT: 'Session Timeout.',
    VALID_PASSWORD:
      'Password must be at least 8 charactor long and contain at least one lowercase, one uppercase charactor and one special charactor.',
    SUCCESS_LOGOUT: 'Logout successfully.',
    OTP_VERIFIED: 'Otp verified successfully.',
    USER_DOES_NOT_EXIST: 'User does not exist.',
    INVALID_OTP: 'Invalid OTP.',
    SUCCESS_PASSWORD_CHANGED: 'Password changed successfully.',
    SUCCESS_PASSWORD_RESET: 'Password reset successfully.',
    PROVIDE_EMAIL: 'Please Provide Email.',
    VERIFY_EMAIL: 'Account verified successfully.',
    ALREADY_VERIFY_EMAIL: 'Email is already Verified.',
    RESEND_EMAIL: 'Email has been sent successfully.',
    USER_NOT_LOGIN: 'You are not logged in! Please login in to continue.',
    SUCCESS_SEND_OTP: 'Otp sent successfully.',
    SUCCESS_USER_UPDATE: 'User updated successfully.',
    SUCCESS_USER_DETAIL_UPDATE: 'User details updated successfully.',
    VALID_EMAIL: 'Enter valid email.',
    PASSWORD_MISMATCH: 'Password and confirm password does not match.',
    FAIL_USER_UPDATE: 'User not updated.',
    USER_DETAILS: 'User details.',
    USER_NOT_FOUND: 'User not found.',
    MOBILE_NUMBER_ALREADY_EXIST:
      'Given mobile number belongs to another user record. Please use a different mobile number.',
    EMAIL_ALREADY_PRESENT:
      'Given email address belongs to another user record. Please use a different email.',
    USERNAME_ALREADY_PRESENT:
      'Given username belongs to another user record. Please use a different username.',
    EMAIL_OR_PHONE_ALREADY_PRESENT:
      'Given email address or Phone Number belongs to another user record. Please use a different .',
    INVALID_CRED: 'Invalid credential.',
    INVALID_CODE: 'Your account has already been verified.',
    INVALID_TOKEN: 'Token Mismatch.',
    SUCCESS_VERFIY_OTP: 'Otp verified successfully.',
  },
};
